ERROR:root:Error: 
Traceback (most recent call last):
  File "C:\Users\Marius Giebenhain\Documents\corona_db\code\helpers\db_reader.py", line 17, in read
    return csv_table(header = header, content = content)
NameError: name 'csv_table' is not defined
ERROR:root:Error: 
Traceback (most recent call last):
  File "C:\Users\Marius Giebenhain\Documents\corona_db\code\helpers\db_reader.py", line 17, in read
    return csv_table(header = header, content = content)
NameError: name 'csv_table' is not defined
ERROR:root:Error: 
Traceback (most recent call last):
  File "C:\Users\Marius Giebenhain\Documents\corona_db\code\helpers\db_reader.py", line 17, in read
    while len(row) != 0:
TypeError: object of type 'NoneType' has no len()
